### ISSUE TITLE
RSS Support

### ISSUE THREAD

**Issue by umpc** [huchenme/github-trending-api#1]
Hello, this is really nice.

Would you consider adding or accepting an ‘output’, or similar, URL parameter for using this with RSS readers?

**Comment by huchenme** [comment]
Unfortunately RSS is not in the scope yet as the main purpose of this API is to feel the gap of GitHub RESTFul API.

I might create a chrome extension to show Trending project on new tab using this API, hope that is something you need

**Comment by huchenme** [comment]
@umpc I think https://github.com/dylang/node-rss is good, Gatsby is using this package as well.

Ideally they would be in separate files for Express, REST API and RSS, so that we could publish npm packages with those modules as well, I would separate them and add some test in next few days.

**Comment by huchenme** [comment]
Closed due to lacking of time
