### ISSUE TITLE
Unable to get results on repositories

### ISSUE THREAD

**Issue by tinchox5** [huchenme/github-trending-api#10]
Hi I'm experimenting problems to fetch data on https://github-trending-api.now.sh/repositories

**Comment by sandoche** [comment]
Yes, the API seems down 😢

**Comment by tinchox5** [comment]
Apparently the problem is just when the API is trying to fetch all coding languages (language=''). This works https://github-trending-api.now.sh/repositories?language=vue

**Comment by huchenme** [comment]
Hi guys, thanks for reporting. Will take a look later today

**Comment by sandoche** [comment]
Good job! Thanks!!
