### ISSUE TITLE
spoken_language_code is Invalid?

### ISSUE THREAD

**Issue by zicjin** [huchenme/github-trending-api#102]
https://github-trending-api.now.sh/repositories?since=weekly&spoken_language_code=English

https://github-trending-api.now.sh/repositories?since=weekly&spoken_language_code=Chinese

The result is the same.

**Comment by huchenme** [comment]
your query parameters are wrong: it should be `en` and `zh`, please refer [this link](https://github-trending-api.now.sh/spoken_languages) for list of languages.

**Comment by zicjin** [comment]
so, Why https://github-trending-api.now.sh/languages could use name to pass parameters. I can use "Emacs Lisp" instead of "emacs-lisp" to get the correct results.

**Comment by zicjin** [comment]
it's interesting.
https://github-trending-api.now.sh/repositories?since=daily&language=common-lisp
https://github-trending-api.now.sh/repositories?since=daily&language=Common-Lisp
The two links get different results. But they are all Common-Lisp projects.
