### ISSUE TITLE
Based on this awesome API

### ISSUE THREAD

**Issue by tinchox5** [huchenme/github-trending-api#11]
Hi @huchenme! Maybe you want to know that I'm working on this project: https://github.com/zircleUI/github-trending-plus that heavily uses your API  😄 🎉
Thank you again for your work!!

**Comment by huchenme** [comment]
Hi @tinchox5, this is nice to know! Your site is fun to play with, nice animations 😄

**Comment by huchenme** [comment]
@tinchox5 Just updated README and added your project to this section https://github.com/huchenme/github-trending-api#projects-using-github-trending-api

🙌

**Comment by tinchox5** [comment]
Thank you!!
