### ISSUE TITLE
repositories endpoint returning empty object

### ISSUE THREAD

**Issue by chrislonge** [huchenme/github-trending-api#13]
`/repositories` is currently returning an empty array when no language is specified. Works fine if you specify a language.

Daily trending repositories seems to be working fine on: https://github.com/trending

**Comment by sandoche** [comment]
I confirm, it looks like the server is down.

**Comment by chrislonge** [comment]
Look's like it's back up now?

**Comment by sandoche** [comment]
Yes!

**Comment by huchenme** [comment]
Sorry I am not sure what was happening, it might be that page was empty at
that time.
