### ISSUE TITLE
Cannot host on Vercel

### ISSUE THREAD

**Issue by sandoche** [huchenme/github-trending-api#131]
Hi,

When I try to host it on Vercel I get the following error:
![image](https://user-images.githubusercontent.com/3635348/95100298-df37e280-0728-11eb-9928-18bc1d6e7fd9.png)

Any idea why?

**Comment by huchenme** [comment]
Not really sure but the version is 2 here: https://github.com/huchenme/github-trending-api/blob/master/now.json#L2
