### ISSUE TITLE
The C# bug

### ISSUE THREAD

**Issue by tinchox5** [huchenme/github-trending-api#14]
Hi @huchenme! Yesterday I posted on HN the experimental example I made using your API. I received some comments informing that when they search 'C#' the results shown are for 'C'. I checked that issue yesterday and the same happens to me. Is there a way to fix that?
Thank you!

**Comment by huchenme** [comment]
You are right, I can reproduce it, will spend sometime tomorrow to fix it.

**Comment by huchenme** [comment]
Hi @tinchox5, the issue has been fixed just now 🙌

https://github-trending-api.now.sh/repositories?language=c%23
https://github.com/trending/c%23?since=daily

**Comment by tinchox5** [comment]
Wow thank you!!!
