### ISSUE TITLE
Can we make repositories.builtBy just an array of usernames?

### ISSUE THREAD

**Issue by wonderbeyond** [huchenme/github-trending-api#22]
For example, we can respond as below

```json
"builtBy": ["timneutkens", "arunoda", "nkzawa", "rauchg"]
```

instead of

```json
"builtBy": [
      {
        "username": "timneutkens",
        "href": "https://github.com/timneutkens",
        "avatar": "https://avatars2.githubusercontent.com/u/6324199"
      },
      {
        "username": "arunoda",
        "href": "https://github.com/arunoda",
        "avatar": "https://avatars3.githubusercontent.com/u/50838"
      },
      {
        "username": "nkzawa",
        "href": "https://github.com/nkzawa",
        "avatar": "https://avatars1.githubusercontent.com/u/775227"
      },
      {
        "username": "rauchg",
        "href": "https://github.com/rauchg",
        "avatar": "https://avatars1.githubusercontent.com/u/13041"
      }
    ]
```

Thus we can reduce much net traffic, and because both the user profile link and avatar link can be derived from **username**:

```javascript
let profileLink = `https://github.com/${username}`;
let avatar = `https://avatars.githubusercontent.com/${username}?s=200&v=4`;
```

---

See also [HitUP](https://hitup.wondertools.top/)'s implementation, which has a `built-by-members` component only consumes the `username` property: https://github.com/wonderbeyond/HitUP/blob/master/src/components/built-by-members/index.js#L9

**Comment by huchenme** [comment]
Unfortunately, this change will be a BREAKING CHANGE for existing API users, unless we setup API versioning.

As each API response is just about 20 records, why is the traffic matter so much to you? is it small any way

**Comment by wonderbeyond** [comment]
My access speed(from Shenzhen China) is not ideal. I just thought how to improve.

Forget it if it's not worth doing.

**Comment by huchenme** [comment]
Sorry going to close this one, if there is enough request for a newer version of API we could reopen this and add it in
