### ISSUE TITLE
Questions about using API.

### ISSUE THREAD

**Issue by Sky24n** [huchenme/github-trending-api#25]
Hi, Huchenme :
 I used this API in my flutter open source project [flutter_wanandroid](https://github.com/Sky24n/flutter_wanandroid).
Your project is very good.Thank you very much!

**Comment by huchenme** [comment]
Thanks, do you mind add your project here: https://github.com/huchenme/github-trending-api/issues/20?

And I will update README as well to list your project

**Comment by huchenme** [comment]
by the way, nice project! 👍
