### ISSUE TITLE
Is it possible to add user type to Trending Developers request?

### ISSUE THREAD

**Issue by khoren93** [huchenme/github-trending-api#29]
Hi again @huchenme )))

For getting user details (for GitHub's GraphQL api) user type (user or organization) is required.
So is it possible to add this param in 'Trending Developers' request?

Thanks!

**Comment by huchenme** [comment]
Could you give an example of required data and parameter?

**Comment by khoren93** [comment]
For example like this
[
    {
      ...
      "username": "google",
      "type": "Organization"
      ...
    }
  ]

**Comment by huchenme** [comment]
as this API gets information from HTML of https://github.com/trending/developers, we could not identify user type there, I could guess that only user will have a "Follow" button?

**Comment by huchenme** [comment]
Sure, I will add this in
