### ISSUE TITLE
Trending Developer API is not working

### ISSUE THREAD

**Issue by rajkstats** [huchenme/github-trending-api#42]
Hey, thank you for this amazing API. It helped me get started with my first web app. Recently, I have seen developer API is not working. Can you take a look?
https://github-trending-api.now.sh/developers?language=R&since=weekly.
Returning no results

**Comment by huchenme** [comment]
@rajkstats thanks for reporting, the GitHub page have been changed and I have just updated code for their change

**Comment by rajkstats** [comment]
Thanks, @huchenme for the link. It's working fine now.

**Comment by rajkstats** [comment]
Hey @huchenme,  again some error on this API endpoint. Something is wrong.
https://github-trending-api.now.sh/developers?language=R&since=weekly

{"username":"antonbabenko","type":"user","url":"https://github.com/antonbabenko","avatar":"https://avatars0.githubusercontent.com/u/393243","repo":{"name":"","description":"","url":"https://github.comundefined"}}

**Comment by huchenme** [comment]
@rajkstats I am not able to see that now :(

**Comment by rajkstats** [comment]
@huchenme  strange, yesterday it was showing empty columns. thanks @huchenme  for looking again.
