### ISSUE TITLE
Do we have popular languages from all languages?

### ISSUE THREAD

**Issue by mirrorhanyu** [huchenme/github-trending-api#52]
Hi @huchenme,

As the description of [https://github-trending-api.now.sh/languages](https://github-trending-api.now.sh/languages) is to retrieve **popular languages** and **all languages**, but popular languages are not showed in response data, is this the expected behaviour?

**Comment by huchenme** [comment]
@mirrorhanyu as GitHub no longer provide popular languages, our languages API will only return a list of languages instead of `popular` and `all`. You could hard code some popular languages yourself
