### ISSUE TITLE
Add new parameter option "Spoken Language" to repositories

### ISSUE THREAD

**Issue by MikeBudimon** [huchenme/github-trending-api#84]
I Think a "Spoken Language" parameter for querying repositories would be beneficial.
See image.
![spoken_language](https://user-images.githubusercontent.com/11709017/71545499-f2dd3e00-298b-11ea-9d9b-6b5628eacf47.PNG)

**Comment by huchenme** [comment]
Great, will add this in

**Comment by sarkiroka** [comment]
Hi @huchenme 
What this filter works based on? How to set the spoken language in a repository?

**Comment by huchenme** [comment]
@sarkiroka something like this: https://ghapi.huchen.dev/repositories?language=javascript&since=weekly&spoken_language_code=en

more parameters here: https://github.com/huchenme/github-trending-api/blob/master/src/spoken-languages.json

**Comment by sarkiroka** [comment]
Okay, I see, this way to read by spoken language. It is great <3
But I don't know what is the base of this filter. I not found how to set spoken language on github repository. I may have been careless.
I tried to filter by hungarian, but no result - I not believe, there is no repository in this language. For example this one is on fully hungarian language: https://github.com/petergerner/alaptorveny
