### ISSUE TITLE
Info: Unofficial trending api

### ISSUE THREAD

**Issue by rajkstats** [huchenme/github-trending-api#89]
Hu Chen, I have been using your API for a hobby project. Some of the folks I have asked me how do you get trending repositories and trending developer (maths behind it). Can you throw some light on that ?. That will be really helpful.

**Comment by huchenme** [comment]
I have written a tutorial here https://medium.com/@chen/how-to-scrape-any-website-and-build-an-api-using-cheerio-js-6a3f0c651d2e?source=friends_link&sk=7b76d9abf0b6c572042238906e281228, and source code is in this repo as well

**Comment by rajkstats** [comment]
Thanks @huchenme for your response and  the tutorial link
